### ISSUE TITLE
Don't nuke refs on copied bins

### ISSUE THREAD

**Issue by 3noch** [3noch/nix-bundle-exe#12]
These are usually scripts that we can't bundle but nuking them breaks them.

**Comment by jp8t-wltr** [comment]
Excuse me for bringing up this long closed issue.  I don't have any particular issue with it, just trying to understand the codebase.

1. May I ask what problem this issue solved?
2. And how did nuking the binaries more sparingly solved it?
3. Why was nuking introduced in the first place?  Is it just to get an accurate description of run-time dependencies when running `nix-store --query --referrers-closure`?

If I understand correctly, nuke-refs will change hidden nix store dependencies in the form of embedded nix store paths.  However since only shared objects are bundled, those embedded store paths even if existing won't be bundled anyhow so closure size won't be reduced.  Moreover nuking them only replaces the paths with =/nix/store/eee...= which will not help with unbreaking anything.

**Comment by 3noch** [comment]
I should probably make nuke-refs an optional step or remove the need for it entirely. The original motivation for this project was to produce a package that has no dependencies on Nix and could be used without it. With that in mind, the Nix closure of a resulting package should be empty. If it's not empty, then you can use that information to help you understand what you have left to fix to completely sever it from Nix.

This feature is more of a hack than anything. The ideal solution is to only "nuke" those references that we have successfully embedded. What I've found is that even after embedding successfully, there are lingering, benign references to the Nix store in some places. This was a way to kill them, but the reality is it goes too far and needs to be even more particular still.

**Comment by jp8t-wltr** [comment]
Thanks for the detailed response!

If it's OK, help me just to clarify:

> there are lingering, benign references to the Nix store in some places. This was a way to kill them

By benign I interpret that you mean they had no effect when executing the built program, is this correct?

Was this implemented in the first place to make sure the output of `nix-store --query --referrers-closure ${OUT_PATH}` is relevant and does not show these benign references?

**Comment by 3noch** [comment]
Yes correct on both.
